// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import LogoSvg from "./logo.svg";

import './App.css';
;

var logo = LogoSvg;

function App$StepButton(Props) {
  return React.createElement("button", undefined, "Step");
}

var StepButton = {
  make: App$StepButton
};

function App$StartStopButton(Props) {
  var match = React.useState(function () {
        return /* Start */0;
      });
  var setState = match[1];
  var currState = match[0];
  var toggleState = function (param) {
    if (currState) {
      return Curry._1(setState, (function (_prev) {
                    return /* Start */0;
                  }));
    } else {
      return Curry._1(setState, (function (_prev) {
                    return /* Stop */1;
                  }));
    }
  };
  var msg = currState ? "Stop" : "Start";
  return React.createElement("button", {
              onClick: toggleState
            }, msg);
}

var StartStopButton = {
  make: App$StartStopButton
};

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(App$StartStopButton, {}), React.createElement(App$StepButton, {}));
}

var make = App;

export {
  logo ,
  StepButton ,
  StartStopButton ,
  make ,
  
}
/*  Not a pure module */
